print(" <!DOCTYPE html>")
print("<html>")
print("<body>")
print("")
print("<p>Click on the 'Choose File' button to upload a file:</p>")
print("")
print("<form action='filetest.py' method='post' enctype='multipart/form-data'>")
print("  <input type='file' id='myFile' name='filename'>")
print("  <input type='submit'>")
print("</form>")
print("")
print("</body>")
print("</html>")
print("</body></html>")