print()
print(" <!DOCTYPE html>")
print("<html>")
print("<body>")
print("")
print("<p>Click on the 'Choose File' button to upload a file:</p>")
print("")
print("<form action='upload_file_result.py' method='post' enctype='multipart/form-data'>")
print("  <input type='file' id='myFile' name='filename'>")
print("  <input type='submit'>")
print("</form>")
print("<p><a href='/cgi-bin/all_files.py'>View all uploaded files</a></p>")
print("")
print("</body>")
print("</html>")